### PR TITLE
add unique constraint,add uniq constraint test in model

### PR DESCRIPTION
**Pull request by erezfree29**
-A unique constraint was added to the friendships table ensuring a new record can not be created with an identical combination of user_id and friend_is as an existing one.
-A test has been added to the friendship model to test that creating an invalid repeated combination is not possible.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @erezfree29 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [ ] When we send the request the other's account is not updating. For example, A send the request to B. B has no buttons for accepting or reject the request. Please update it, it was the requirement for the last milestone, but this project is the extension of the last milestone please ensure the last functionalities and update the code like the following.
- [ ] We tested the project in your system because there were issues on `rails db:brop`, `rails db:create` and `rails db:migrate` on your system too. Please fix them.
- [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created
```
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

```
- [ ] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```
# User model
# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships

```

- [ ] In order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables)
```
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end

```
- [ ] Due to Migration and bundle inssues I'm not able to test the test cases
- Users got links to [this artcile](https://explainextended.com/2009/03/07/selecting-friends) and [stackoverflow discussion](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table) as a hint.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
-------------
Hello @erezfree29 Great job working on the required changes :clap: 
However, there is still one problem to solve :hammer_and_wrench:  see it below :point_down: :eyes: 
-----------

- [ ] when I run RSpec I got the following error. 

Screenshot from 2021-05-11 11-29-10
-------------
Make the required changes and send it again for another review :smile: 
HAPPY CODING!! :+1:

**Comment by erezfree29** [comment]
Hello 
I ran Rspec and did not get the error above.
when I ran Rspec in the root folder it did not check all the files but I was able to check each of them individually by running from the root folder for example
rspec spec/models/user.spec.rb

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
**Hi Erez!
Great job so far:clap:. We are almost there. However, we just need to make this change to get the project approved:muscle:.**

**To improve**

- [ ] When I run `bundle exec rspec`. Only three tests are passing. But I can see a lot of the tests you implemented in the project codebase. See [screen-shot](https://imgur.com/a/k1ZXbNj) for reference. Kindly fix this.

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Comment by erezfree29** [comment]
As I have written in my last comment running  the tests can be run individually buy running 
rspec spec/models/comment.spec.rb
rspec spec/models/friendship.spec.rb
rspec spec/models/like.spec.rb
rspec spec/models/post.spec.rb
rspec spec/models/user.spec.rb
rspec spec/feature/user_sign_in.spec.rb
rspec spec/feature/user_sign_up.spec.rb

**Review by GzimAsani — APPROVED** [review]
# STATUS: Millstone Accepted :green_circle: :partying_face: 

## Hello **Team**, thank you for making all the required changes. I can see that you worked hard and you did an amazing job, you can merge now and continue in the next millstone. Very best luck :+1: 

_**PS: Don't forget to submit the project completion form :thought_balloon:**_

**Pull request merged**
